NelitaBeautyStudio.Web/Controllers/ContactsController.cs
namespace NelitaBeautyStudio.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper;

    using NelitaBeautyStudio.Common;
    using NelitaBeautyStudio.Data.Unit_of_Work;
    using NelitaBeautyStudio.Models;
    using NelitaBeautyStudio.Web.Infrastructure;
    using NelitaBeautyStudio.Web.ViewModels;

    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class ContactsController : BaseController
    {
        public ContactsController(IApplicationData data)
            : base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var contacts = this.Data.Contacts.All()
                .OrderByDescending(c => c.Priority)
                .ThenBy(c => c.Type)
                .ToList();

            return this.View("Index", contacts);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContactViewModel contact)
        {
            if (ModelState.IsValid)
            {
                var contactEntity = Mapper.Map<Contact>(contact);
                this.Data.Contacts.Add(contactEntity);
                this.Data.SaveChanges();

                this.Notify(GlobalConstants.AddContact, NotificationType.success);

                return this.RedirectToAction("Index");
            }

            return this.View(contact);
        }

        public ActionResult Edit(int id)
        {
            var contact = this.Data.Contacts.GetById(id);
            var contactViewModel = Mapper.Map<ContactViewModel>(contact);

            return this.View(contactViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ContactViewModel contact)
        {
            if (ModelState.IsValid)
            {
                var updatedContact = Mapper.Map<Contact>(contact);
                updatedContact.Id = id;
                this.Data.Contacts.Update(updatedContact);
                this.Data.SaveChanges();

                this.Notify(GlobalConstants.EditContact, NotificationType.success);

                return this.RedirectToAction("Index");
            }

            return this.View(contact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var contact = this.Data.Contacts.GetById(id);

            this.Data.Contacts.Delete(contact);
            this.Data.SaveChanges();

            this.Notify(GlobalConstants.DeleteContact, NotificationType.info);

            return this.RedirectToAction("Index");
        }
    }
}

NelitaBeautyStudio.Web/Controllers/PriceListController.cs
namespace NelitaBeautyStudio.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper;

    using NelitaBeautyStudio.Common;
    using NelitaBeautyStudio.Data.Unit_of_Work;
    using NelitaBeautyStudio.Models;
    using NelitaBeautyStudio.Web.Infrastructure;
    using NelitaBeautyStudio.Web.ViewModels;

    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class PriceListController : BaseController
    {
        public PriceListController(IApplicationData data)
            : base(data)
        {
        }

        [ChildActionOnly]
        [AllowAnonymous]
        public ActionResult PriceListDropDown()
        {
            var priceLists = this.Data.PriceLists.All().ToList();

            return this.PartialView(priceLists);
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var priceList = this.Data.PriceLists.GetById(id);

            return this.View(priceList);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PriceListViewModel priceList)
        {
            var titleAlreadyExists = this.Data.PriceLists.All().FirstOrDefault(p => p.Title == priceList.Title) != null;

            if (titleAlreadyExists)
            {
                ModelState.AddModelError("Title", "Не може да се добави втори ценоразпис с това име!");

                return this.View(priceList);
            }

            if (ModelState.IsValid)
            {
                var priceListModel = Mapper.Map<PriceList>(priceList);

                this.Data.PriceLists.Add(priceListModel);
                this.Data.SaveChanges();

                this.Notify(GlobalConstants.AddPriceList, NotificationType.success);

                return this.RedirectToAction("Details", new { id = priceListModel.Id });
            }

            return this.View(priceList);
        }

        public ActionResult Edit(int id)
        {
            var priceList = this.Data.PriceLists.GetById(id);
            var priceListViewModel = Mapper.Map<PriceListViewModel>(priceList);

            return this.View(priceListViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PriceListViewModel priceList)
        {
            var titleAlreadyExists = this.Data.PriceLists.All().FirstOrDefault(p => p.Title == priceList.Title) != null;

            if (titleAlreadyExists)
            {
                ModelState.AddModelError("Title", "Не може да се добави втори ценоразпис с това име!");

                return this.View(priceList);
            }

            if (ModelState.IsValid)
            {
                var priceListModel = Mapper.Map<PriceList>(priceList);
                priceListModel.Id = id;

                this.Data.PriceLists.Update(priceListModel);
                this.Data.SaveChanges();

                this.Notify(GlobalConstants.EditPriceList, NotificationType.success);

                return this.RedirectToAction("Details", new { id = priceListModel.Id });
            }

            return this.View(priceList);
        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            var priceList = this.Data.PriceLists.GetById(id);
            var priceListViewModel = Mapper.Map<PriceListViewModel>(priceList);

            return this.View(priceListViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var priceList = this.Data.PriceLists.GetById(id);

            this.Data.PriceLists.Delete(priceList);
            this.Data.SaveChanges();

            this.Notify(GlobalConstants.DeletePriceList, NotificationType.warning);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

NelitaBeautyStudio.Web/Controllers/RolesController.cs
namespace NelitaBeautyStudio.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    
    using NelitaBeautyStudio.Common;
    using NelitaBeautyStudio.Data.Unit_of_Work;
    using NelitaBeautyStudio.Models;
    using NelitaBeautyStudio.Web.Infrastructure;
    using NelitaBeautyStudio.Web.ViewModels;

    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class RolesController : BaseController
    {
        public RolesController(IApplicationData data)
            : base(data)
        {
        }

        public ActionResult Manage()
        {
            var users = this.Data.Users.All()
                .OrderBy(u => u.Email)
                .ToList();
            var adminRole = this.Data.Roles.All().First(r => r.Name == GlobalConstants.AdminRole);
            var model = new ManageUserRolesViewModel() { AdminRole = adminRole, Users = users };

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Promote(string id)
        {
            var store = new UserStore<User>(this.Data.Context);
            var manager = new UserManager<User>(store);

            manager.AddToRoleAsync(id, GlobalConstants.AdminRole);

            this.Notify(GlobalConstants.PromoteUser, NotificationType.success);

            return this.RedirectToAction("Manage");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Demote(string id)
        {
            var currentUser = this.Data.Users.All().First(u => u.UserName == User.Identity.Name);
            var isSameUser = id == currentUser.Id;

            if (!isSameUser)
            {
                var store = new UserStore<User>(this.Data.Context);
                var manager = new UserManager<User>(store);

                manager.RemoveFromRoleAsync(id, GlobalConstants.AdminRole);

                this.Notify(GlobalConstants.DemoteUserSuccess, NotificationType.success);
            }
            else
            {
                this.Notify(GlobalConstants.DemoteUserFail, NotificationType.error);
            }

            return this.RedirectToAction("Manage");
        }
    }
}

NelitaBeautyStudio.Web/Views/Shared/_Layout.cshtml
@using NelitaBeautyStudio.Common

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Салон за красота "Нелита"</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/toastr")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Салон за красота \"Нелита\"", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Услуги <span class="caret"></span>
                        </a>
                        
                        @Html.Action("PriceListDropDown", "PriceList")
                    </li>
                    <li>@Html.ActionLink("Контакти", "Index", "Contacts")</li>

                    @if (User.IsInRole(GlobalConstants.AdminRole))
                    {
                        <li>@Html.ActionLink("Управление на администраторите", "Manage", "Roles")</li>
                    }
                    
                    @if (User.IsInRole(GlobalConstants.AdminRole))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Новини <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Добави", "Create", "News")</li>
                                <li>@Html.ActionLink("Виж всички", "Index", "News")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Новини", "Index", "News")</li>
                    }
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - <a href="https://github.com/Rossoner40/NelitaBeautyStudio" target="_blank">NelitaBeautyStudio</a> е проект с отворен код.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>