NelitaBeautyStudio.Web/ViewModels/ServiceViewModel.cs
namespace NelitaBeautyStudio.Web.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    using NelitaBeautyStudio.Common;

    public class ServiceViewModel
    {
        [Display(Name = "Услуга")]
        [Required(ErrorMessage = "Полето {0} е задължително")]
        [StringLength(
            GlobalConstants.TextFieldLengthMax,
            ErrorMessage = "Полето {0} трябва да бъде между {2} и {1} символа!",
            MinimumLength = GlobalConstants.TextFieldLengthMin)]
        public string Type { get; set; }

        [Display(Name = "Цена")]
        [Required(ErrorMessage = "Полето {0} е задължително")]
        [Range(GlobalConstants.PriceMinimum, GlobalConstants.PriceMaximum, ErrorMessage = "Полето {0} трябва да бъде между {1} и {2} лева!")]
        public double Price { get; set; }
    }
}

NelitaBeautyStudio.Web/Controllers/ServiceController.cs
namespace NelitaBeautyStudio.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper;
    
    using NelitaBeautyStudio.Common;
    using NelitaBeautyStudio.Data.Unit_of_Work;
    using NelitaBeautyStudio.Web.Infrastructure;
    using NelitaBeautyStudio.Web.ViewModels;

    public class ServiceController : BaseController
    {
        public ServiceController(IApplicationData data)
            : base(data)
        {
        }

        public ActionResult Create(string priceListTitle)
        {
            this.ViewData["priceList"] = priceListTitle;

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ServiceViewModel service, string priceListTitle)
        {
            if (ModelState.IsValid)
            {
                var serviceModel = Mapper.Map<NelitaBeautyStudio.Models.Service>(service);
                var priceList = this.Data.PriceLists.All().FirstOrDefault(p => p.Title == priceListTitle);

                serviceModel.PriceList = priceList;

                this.Data.Services.Add(serviceModel);
                this.Data.SaveChanges();

                this.Notify(GlobalConstants.AddService, NotificationType.success);

                return this.RedirectToAction("Details", "PriceList", new { id = priceList.Id });
            }

            return this.View(service);
        }

        public ActionResult Edit(int id)
        {
            var service = this.Data.Services.GetById(id);
            var serviceViewModel = Mapper.Map<ServiceViewModel>(service);

            return this.View(serviceViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ServiceViewModel service)
        {
            if (ModelState.IsValid)
            {
                var serviceModel = this.Data.Services.GetById(id);
                serviceModel.Type = service.Type;
                serviceModel.Price = service.Price;

                this.Data.Services.Update(serviceModel);
                this.Data.SaveChanges();

                this.Notify(GlobalConstants.EditService, NotificationType.success);

                return this.RedirectToAction("Details", "PriceList", new { id = serviceModel.PriceList.Id });
            }

            return this.View(service);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var service = this.Data.Services.GetById(id);
            var priceListId = service.PriceList.Id;

            this.Data.Services.Delete(service);
            this.Data.SaveChanges();

            this.Notify(GlobalConstants.DeleteService, NotificationType.info);

            return this.RedirectToAction("Details", "PriceList", new { id = priceListId });
        }
    }
}

NelitaBeautyStudio.Web/Views/Service/Create.cshtml
@using NelitaBeautyStudio.Web.ViewModels
@model ServiceViewModel
@{
    ViewBag.Title = "Нова услуга";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Нова услуга за @ViewData["priceList"]</h2>

@using (Html.BeginForm("Create", "Service", new { priceListTitle = ViewData["priceList"] }, FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(s => s.Type, new { @class = "col-lg-2 control-label" })
        @Html.EditorFor(s => s.Type)
        @Html.ValidationMessageFor(s => s.Type, null, new { @class = "alert-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(s => s.Price, new { @class = "col-lg-2 control-label" })
        @Html.EditorFor(s => s.Price)
        @Html.ValidationMessageFor(s => s.Price, null, new { @class = "alert-danger" })
    </div>
    
    <input type="submit" value="Добави" class="btn btn-primary">
    
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NelitaBeautyStudio.Web/Views/Service/Edit.cshtml
@using NelitaBeautyStudio.Web.ViewModels
@model ServiceViewModel
@{
    ViewBag.Title = "Редактиране на услуга";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактиране на услуга</h2>

@using (Html.BeginForm("Edit", "Service", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(s => s.Type, new { @class = "col-lg-2 control-label" })
        @Html.EditorFor(s => s.Type)
        @Html.ValidationMessageFor(s => s.Type, null, new { @class = "alert-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(s => s.Price, new { @class = "col-lg-2 control-label" })
        @Html.EditorFor(s => s.Price)
        @Html.ValidationMessageFor(s => s.Price, null, new { @class = "alert-danger" })
    </div>

    <input type="submit" value="Редактирай" class="btn btn-warning">

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}